name 'audit-telnet'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures audit-telnet'
long_description 'Installs/Configures audit-telnet'
version '0.1.0'
