name 'update_packages'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures update_packages'
long_description 'Installs/Configures update_packages'
version '0.1.0'
