name 'audit-cve'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures audit-cve'
long_description 'Installs/Configures audit-cve'
version '0.1.0'
